FROM node:13.2

ARG PACKAGE_PATH=.
ARG WORKING_DIR=/src

WORKDIR $WORKING_DIR
COPY $PACKAGE_PATH/package.json $WORKING_DIR/package.json
RUN npm install

COPY $PACKAGE_PATH $WORKING_DIR

VOLUME $WORKING_DIR/node_modules
CMD [ "npm", "run", "build" ]