version: "2.1"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.node
      args:
        PACKAGE_PATH: .
        WORKING_DIR: /src
    env_file:
      - ../background-geolocation-console-secrets.env
    command: ["npm", "start"]
